# Generated by Django 4.2.4 on 2023-10-04 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0004_remove_taks_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Taks',
        ),
    ]
