# Generated by Django 4.2.4 on 2023-10-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0008_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taks',
            new_name='Task',
        ),
    ]
