# Generated by Django 4.2.4 on 2023-10-07 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profesores', '0001_initial'),
        ('LoungeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers_lounges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoungeApp.lounge')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profesores.teacher')),
            ],
        ),
    ]
